export const List = [
  {
    title: "Smart, Fast & Reliable",
    span: "Airport Trips",
    text: "Never miss a flight or wait for a ride again! Our smart, fast, and reliable airport transfer service guarantees on-time pickups and drop-offs, ensuring a smooth and stress-free journey. Whether you're heading to the airport for an early morning flight or arriving late at night, we are available 24/7 to provide safe and comfortable transport. With professional drivers, well-maintained vehicles, and a commitment to punctuality, we make every airport trip seamless.",
    img: "/Tplan.jpg",
    button: "Book Now",
    location: "/airportLearn",
  },
  {
    title: "Fast & Reliable",
    span: "City Rides ",
    text: "Navigating the city has never been easier! Our fast and reliable city ride service ensures that you get where you need to be—quickly, safely, and comfortably. Whether you're commuting to work, attending a business meeting, shopping, or enjoying a night out, we provide a hassle-free transport experience. Our fleet of well-maintained vehicles and professional drivers ensure every ride is efficient, affordable, and secure.",
    img: "/City.jpg",
    button: "Book Now",
    location: "/airportLearn",
  },
  {
    title: "Smart",
    span: "Car Hire",
    text: "Need a car for a few hours, a day, or even a month? Our exotic,  smart car hire service gives you access to a fleet of well-maintained, fuel-efficient, and comfortable vehicles suited for personal and business use. Whether you're traveling out of town, running errands, or need a temporary replacement car, we provide affordable rates, flexible rental plans, and a seamless booking process. With us, you get the convenience of a private vehicle without the stress of ownership.",
    img: "/Cars.jpg",
    button: "Hire Now",
    location: "/carLearn",
  },
  {
    title: "Fast & Reliable",
    span: "Couier Services",
    text: "We understand the importance of fast and secure deliveries. Our intown and intercity smart, fast, and reliable courier service ensures your packages, documents, and parcels reach their destination on time and in perfect condition. Whether it's an urgent business document, a fragile package, we provide real-time tracking, safe handling, and efficient delivery. Trust us to move your parcels with care and speed.",
    img: "/Courier.jpg",
    button: "Try Now",
    location: "/courierLearn",
  },
  {
    title: "Smart",
    span: "Driver Hire",
    text: "Looking for a skilled and professional driver? Our smart driver hire service connects you with experienced, background-checked, and reliable drivers for both short-term and long-term needs. Whether you require a driver for a personal trip, corporate service, or special occasion, we ensure you get a safe, punctual, and professional chauffeur. Enjoy a smooth ride while we take care of the driving",
    img: "/Driver.jpg",
    button: "Hire Now",
    location: "/driverlearn",
  },
  {
    title: "Smart",
    span: "Investment",
    text: "Turn your vehicle into a profitable asset with our smart investment opportunity! We offer a structured investment plan where you can lease your car to us and earn steady, reliable income. With our hassle-free management, timely payments, and full operational handling, you can enjoy a stress-free investment while watching your money grow. Partner with us today and secure a brighter financial future!",
    img: "/investt.jpg",
    button: "Try Now",
    location: "/invest",
  },
];
